# Generated by Django 3.0.7 on 2020-07-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.IntegerField(default='')),
                ('date', models.DateField(default='')),
                ('time', models.TimeField(default='')),
                ('tour', models.CharField(default='', max_length=50)),
                ('price', models.CharField(default='', max_length=50)),
                ('total', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookTour',
            fields=[
                ('booktour_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger', models.IntegerField(default='')),
                ('tour', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default='')),
                ('time', models.TimeField(default='')),
                ('price', models.CharField(default='', max_length=50)),
                ('total', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=10)),
                ('country', models.CharField(default='', max_length=25)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default='')),
                ('month', models.IntegerField(default='')),
                ('year', models.IntegerField(default='')),
                ('second', models.IntegerField(default='')),
                ('minute', models.IntegerField(default='')),
                ('hour', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('day', models.IntegerField(default='')),
                ('month', models.IntegerField(default='')),
                ('year', models.IntegerField(default='')),
                ('phone', models.CharField(default='', max_length=10)),
                ('country', models.CharField(default='', max_length=25)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger', models.IntegerField(default='')),
                ('tour', models.CharField(default='', max_length=50)),
                ('price', models.CharField(default='', max_length=50)),
                ('total', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.IntegerField(default='')),
                ('tour', models.CharField(default='', max_length=50)),
                ('price', models.CharField(default='', max_length=50)),
                ('total', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
